name: Update M3U

on:
  workflow_dispatch:

  schedule:
    - cron: "*/30 * * * *"

permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install requests
        run: |
          pip install requests

      - name: Run JSON to M3U converter
        env:
          SOURCE_URL: ${{ secrets.SOURCE_URL }}
        run: |
          python source.py

      - name: Commit updated M3U
        run: |

          git config user.name "github-actions[bot]"

          git config user.email \
            "41898282+github-actions[bot]@users.noreply.github.com"

          git add events.m3u

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update M3U playlist"
            git push
          fi
