name: Auto Update M3U

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Requests
        run: pip install requests

      - name: Generate M3U
        env:
          API_URL: ${{ secrets.API_URL }}
          COOKIE_URL: ${{ secrets.COOKIE_URL }}
        run: |
          python <<'EOF'
          print("test")
          EOF

      - name: Commit Files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add jtv.m3u
          git commit -m "Auto update playlist" || echo "No changes"
          git push
