name: Hotstar Auto Update

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pywidevine

      - name: Run extractor
        env:
          HOTSTAR_TOKEN: ${{ secrets.HOTSTAR_TOKEN }}
          HOTSTAR_URL: ${{ secrets.HOTSTAR_URL }}
        run: |
          python hot_github.py

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add .
          git commit -m "Auto update playlist" || echo "No changes"

          git push
