name: Update M3U8

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
                python -m pip install --upgrade pip
                pip install requests    

      - name: Run generator
        env:
          SOURCE_URL: ${{ secrets.SOURCE_URL }}
        run: python generate.py

      - name: Commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add fifa2k26.m3u8
          git diff --cached --quiet || (
            git commit -m "Update playlist"
            git push
          )
